spring:
  profiles: production
  datasource:
    url: jdbc:mysql://localhost:3306/aim_db?serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: aim_user
    password: your_pass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
