spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:~/aimAdviceServerApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console