spring:
  profiles:
    default: local

  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: w7VmYkZQTk13R0tnUE5YS1Y2c2doQ1ZuV09tWXBUWkg=
